[package]
name = "at_vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
at_syntax = { path = "../at_syntax" }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
at_parser = { path = "../at_parser" }
