[package]
name = "at_lint"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
at_syntax = { path = "../at_syntax" }
toml = "0.8"

[dev-dependencies]
at_parser = { path = "../at_parser" }
