[package]
name = "at_lint"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
at_check = { path = "../at_check" }
at_syntax = { path = "../at_syntax" }
toml = "0.9"

[dev-dependencies]
at_parser = { path = "../at_parser" }
